name: workflow_01

on: push

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64

      - name: Instalar pipenv
        run: pip install pipenv

      - name: Instalar dependências
        run: pipenv sync --dev

      - name: Rodar flake8
        run: pipenv run flake8

      - name: 'Generate requirements.txt'
        run: |
            pipx run pipfile-requirements Pipfile.lock > requirements.txt

      - uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          inputs: requirements.txt
